#服务端口
server:
  port: 18080
spring:
  application:
    name: tanhua-app-server
  redis:  #redis配置
    port: 6379
    host: 192.168.136.160
  cloud:  #nacos配置
    nacos:
      discovery:
        server-addr: 192.168.136.160:8848
dubbo:    #dubbo配置
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false
tanhua:
  sms:
    signName: ABC商场
    templateCode: SMS_463631983
    accessKey: LTAI5tCTNWWyzHnFK3sCnbGA
    secret: aQltzJU4ICvPeuj9dw09RtDGvIsrsX
  oss:
    accessKey: LTAI5tCTNWWyzHnFK3sCnbGA
    secret: aQltzJU4ICvPeuj9dw09RtDGvIsrsX
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: pirmingham-sky-take-out
    url: https://pirmingham-sky-take-out.oss-cn-beijing.aliyuncs.com/
  aip:
    appId: 40566885
    apiKey: MbsvRG7EBqg7ImVfQjRWb4ko
    secretKey: g6qikoQNW15vwrxA4BsaYiaGOmiKq371